<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>SWGSurvivors_Patcher</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ApplicationIcon>swgs.ico</ApplicationIcon>
    <AssemblyName>SWGSurvivors-Patcher</AssemblyName>
    <Version>0.2.3</Version>
    <!-- FileVersion and AssemblyVersion will auto-generate -->
    <Authors>Quandru</Authors>
    <Company>SWGSurvivors</Company>
    <Product>SWGSurvivors Delta Patcher</Product>
    <Description>Lightweight delta patcher for SWGSurvivors with self-update capability</Description>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="logo.png" />
  </ItemGroup>

</Project>
